package com.example.projekakhirpam.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLightContrast = Color(0xFF004D33)
val onPrimaryLightContrast = Color(0xFFFFFFFF)
val primaryContainerLightContrast = Color(0xFF3C8161)
val onPrimaryContainerLightContrast = Color(0xFFFFFFFF)
val secondaryLightContrast = Color(0xFF32473C)
val onSecondaryLightContrast = Color(0xFFFFFFFF)
val secondaryContainerLightContrast = Color(0xFF637A6C)
val onSecondaryContainerLightContrast = Color(0xFFFFFFFF)
val tertiaryLightContrast = Color(0xFF294174)
val onTertiaryLightContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightContrast = Color(0xFF5C74A9)
val onTertiaryContainerLightContrast = Color(0xFFFFFFFF)
val errorLightContrast = Color(0xFF8C0009)
val onErrorLightContrast = Color(0xFFFFFFFF)
val errorContainerLightContrast = Color(0xFFDA342E)
val onErrorContainerLightContrast = Color(0xFFFFFFFF)
val backgroundLightContrast = Color(0xFFF5FBF4)
val onBackgroundLightContrast = Color(0xFF171D19)
val surfaceLightContrast = Color(0xFFF5FBF4)
val onSurfaceLightContrast = Color(0xFF171D19)
val surfaceVariantLightContrast = Color(0xFFDCE5DD)
val onSurfaceVariantLightContrast = Color(0xFF3C453F)
val outlineLightContrast = Color(0xFF58615B)
val outlineVariantLightContrast = Color(0xFF747D76)
val scrimLightContrast = Color(0xFF000000)
val inverseSurfaceLightContrast = Color(0xFF2C322E)
val inverseOnSurfaceLightContrast = Color(0xFFEDF2EC)
val inversePrimaryLightContrast = Color(0xFF8FD5B0)
val surfaceDimLightContrast = Color(0xFFD6DBD5)
val surfaceBrightLightContrast = Color(0xFFF5FBF4)
val surfaceContainerLowestLightContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightContrast = Color(0xFFF0F5EF)
val surfaceContainerLightContrast = Color(0xFFEAEFE9)
val surfaceContainerHighLightContrast = Color(0xFFE4EAE3)
val surfaceContainerHighestLightContrast = Color(0xFFDEE4DE)

val primaryDarkContrast = Color(0xFF93DAB4)
val onPrimaryDarkContrast = Color(0xFF001B0F)
val primaryContainerDarkContrast = Color(0xFF599E7C)
val onPrimaryContainerDarkContrast = Color(0xFF000000)
val secondaryDarkContrast = Color(0xFFB8D1C1)
val onSecondaryDarkContrast = Color(0xFF051A10)
val secondaryContainerDarkContrast = Color(0xFF7F9688)
val onSecondaryContainerDarkContrast = Color(0xFF000000)
val tertiaryDarkContrast = Color(0xFFB6CAFF)
val onTertiaryDarkContrast = Color(0xFF001439)
val tertiaryContainerDarkContrast = Color(0xFF7990C7)
val onTertiaryContainerDarkContrast = Color(0xFF000000)
val errorDarkContrast = Color(0xFFFFBAB1)
val onErrorDarkContrast = Color(0xFF370001)
val errorContainerDarkContrast = Color(0xFFFF5449)
val onErrorContainerDarkContrast = Color(0xFF000000)
val backgroundDarkContrast = Color(0xFF0F1511)
val onBackgroundDarkContrast = Color(0xFFDEE4DE)
val surfaceDarkContrast = Color(0xFF0F1511)
val onSurfaceDarkContrast = Color(0xFFF7FCF6)
val surfaceVariantDarkContrast = Color(0xFF404943)
val onSurfaceVariantDarkContrast = Color(0xFFC4CDC5)
val outlineDarkContrast = Color(0xFF9CA59E)
val outlineVariantDarkContrast = Color(0xFF7C857E)
val scrimDarkContrast = Color(0xFF000000)
val inverseSurfaceDarkContrast = Color(0xFFDEE4DE)
val inverseOnSurfaceDarkContrast = Color(0xFF262B27)
val inversePrimaryDarkContrast = Color(0xFF005337)
val surfaceDimDarkContrast = Color(0xFF0F1511)
val surfaceBrightDarkContrast = Color(0xFF353B36)
val surfaceContainerLowestDarkContrast = Color(0xFF0A0F0C)
val surfaceContainerLowDarkContrast = Color(0xFF171D19)
val surfaceContainerDarkContrast = Color(0xFF1B211D)
val surfaceContainerHighDarkContrast = Color(0xFF262B27)
val surfaceContainerHighestDarkContrast = Color(0xFF303632)








